image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip

before_script:
  - python -m pip install --upgrade pip  # For debugging
  - python -m pip install pytest
  - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  - pip install .        
        
test:
  script:
    - pytest